config/routes.rb
CheetStock::Application.routes.draw do
  root :to => 'sheets#index'

  resources :groups do
    collection do
      post 'reorder'
    end
    resources :key_mappings do
      collection do
        post 'reorder'
      end
    end
  end

end

app/models/group.rb
class Group < MyBaseModel
  has_many :key_mappings, dependent: :destroy
  belongs_to :sheet
  default_scope order(['groups.column_no', 'groups.ordinal'])
end

app/models/key_mapping.rb
class KeyMapping < MyBaseModel
  belongs_to :group
  
  attr_protected :group_id
end

app/models/my_base_model.rb
class MyBaseModel < ActiveRecord::Base
  self.abstract_class = true
  
  def self.next_ordinal
    ordinal = self.maximum(:ordinal) || 0
    ordinal += 1
  end
end

app/models/sheet.rb
class Sheet < ActiveRecord::Base
  has_many :groups
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  private
  def xhr_response_render_json(status)
    msg = (status)? 'success' : 'error'
    hash = { status: msg }
    hash.merge!(yield) if block_given?
    render json: hash
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :find_group, :only => [:show, :edit, :update, :destroy]
  def reorder
    params[:group].each_with_index{|row, i| Group.update(row, {ordinal: i + 1})}
    render :nothing => true
  end

  def index
    @groups = Group.all
  end

  def show
  end

  def new
    @group = Group.new
  end

  def edit
  end

  def create
    @group = Group.new(params[:group])
    if request.xhr?
      @group.ordinal = Group.next_ordinal
      @group.key_mappings.build({key: '', content: '', ordinal: 1})
    end
    
    status = @group.save
    if request.xhr?
      xhr_response_render_json(status) do
        html = render_to_string partial: 'shared/group', collection: [@group]
        {html: html}
      end
      return
    end

    if status
      redirect_to @group, notice: 'Group was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    status = @group.update_attributes(params[:group])
    xhr_response_render_json(status) and return if request.xhr?

    if status
      redirect_to @group, notice: 'Group was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    status = @group.destroy
    xhr_response_render_json(status) and return if request.xhr?
    redirect_to groups_url
  end
  
  private
  def find_group
    @group = Group.find(params[:id])
  end
end

app/controllers/key_mappings_controller.rb
class KeyMappingsController < ApplicationController
  before_filter :find_key_mapping, :only => [:show, :edit, :update, :destroy]

  def reorder
    # グループ間を移動する場合
    increment_id = get_increment_id(params[:keymapping], params[:group_id])
    logger.info { "xxxxxxxxxxxxxxxx" }
    logger.info { increment_id }
    logger.info { "" }
    logger.info { "" }
    if increment_id
      add_key_mapping = KeyMapping.find(increment_id)
      add_key_mapping.group_id = params[:group_id]
      add_key_mapping.save!
    end

    params[:keymapping].each_with_index{|row, i| KeyMapping.update(row, {ordinal: i + 1})}
    render :nothing => true
  end

  def index
    @group_id = params[:group_id]
    @key_mappings = KeyMapping.where(group_id: @group_id)
  end

  def show
  end

  def new
    @key_mapping = KeyMapping.new
    @group = Group.find(params[:group_id])
  end

  def edit
    @group = @key_mapping.group
  end

  def create
    group_id = params[:group_id]
    @key_mapping = KeyMapping.new(params[:key_mapping])
    @key_mapping.group_id = group_id

    @key_mapping.ordinal = KeyMapping.next_ordinal if request.xhr?
    
    status = @key_mapping.save
    if request.xhr?
      xhr_response_render_json(status) do
        html = render_to_string partial: 'shared/key_mapping', collection: [@key_mapping]
        {html: html}
      end
      return
    end
    if status
      redirect_to group_key_mapping_path(group_id, @key_mapping), notice: 'Key mapping was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    status =  @key_mapping.update_attributes(params[:key_mapping])
    xhr_response_render_json(status) and return if request.xhr?
    if status
      redirect_to [:group, @key_mapping], notice: 'Key mapping was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    status = @key_mapping.destroy
    # if last_item?
    #   status = @key_mapping.update_attributes({key: '', content: '', ordinal: 1})
    # else
    #   status = @key_mapping.destroy
    # end
    xhr_response_render_json(status) and return if request.xhr?
    redirect_to group_key_mappings_path
  end

  
  private
  def find_key_mapping
    @key_mapping = KeyMapping.find(params[:id])
  end

  def get_increment_id(key_mapping_ids, group_id)
    bef_keys = KeyMapping.where(group_id: group_id).map(&:id)
    aft_keys = key_mapping_ids.map(&:to_i)
    (aft_keys - bef_keys)[0]
  end

  # def last_item?(group_id)
  #   KeyMapping.where(group_id: group_id).size == 1
  # end
end

app/controllers/sheets_controller.rb
class SheetsController < ApplicationController
  def index
    @sheet = Sheet.find(1) # TODO: userと絡める
    # column_no毎にグループ化
    @groups = {}
    groups = Group.order('groups.ordinal, key_mappings.ordinal').includes(:key_mappings)
    groups.chunk{|group| group.column_no }.each{ |k,v| @groups[k] = v }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/key_mappings_helper.rb
module KeyMappingsHelper
end

app/helpers/sheets_helper.rb
module SheetsHelper

  def key_option(km)
    " nodata" if km.key.blank? and km.content.blank? 
  end
  
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :ordinal %><br />
    <%= f.number_field :ordinal %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<h1>Listing groups</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Ordinal</th>
    <th>KeyMappings数</th>
    <th>Links</th>
  </tr>

<% @groups.each do |group| %>
  <tr>
    <td><%= group.name %></td>
    <td><%= group.ordinal %></td>
    <td><%= group.key_mappings.size %></td>
    <td><%= link_to 'KeyMappings', group_key_mappings_path(group) %>
        <%= link_to 'Show', group %>
        <%= link_to 'Edit', edit_group_path(group) %>
        <%= link_to 'Destroy', group, method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @group.name %>
</p>

<p>
  <b>Ordinal:</b>
  <%= @group.ordinal %>
</p>


<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>

app/views/key_mappings/_form.html.erb
<%= form_for([@group, @key_mapping]) do |f| %>
  <% if @key_mapping.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@key_mapping.errors.count, "error") %> prohibited this key_mapping from being saved:</h2>

      <ul>
      <% @key_mapping.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :key %><br />
    <%= f.text_field :key %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :ordinal %><br />
    <%= f.number_field :ordinal %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/key_mappings/edit.html.erb
<h1>Editing key_mapping</h1>

<%= render 'form' %>

<%= link_to 'Show', group_key_mappings_path(@group, @key_mapping) %> |
<%= link_to 'Back', group_key_mappings_path %>

app/views/key_mappings/index.html.erb
<h1>Listing key_mappings</h1>

<table>
  <tr>
    <th>Key</th>
    <th>Content</th>
    <th>Ordinal</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @key_mappings.each do |key_mapping| %>
  <tr>
    <td><%= key_mapping.key %></td>
    <td><%= key_mapping.content %></td>
    <td><%= key_mapping.ordinal %></td>
    <td><%= link_to 'Show', group_key_mapping_path(@group_id, key_mapping) %></td>
    <td><%= link_to 'Edit', edit_group_key_mapping_path(@group_id, key_mapping) %></td>
    <td><%= link_to 'Destroy', group_key_mapping_path(@group_id, key_mapping), method: :delete %></td>
  </tr>
<% end %>
</table>

<br />
<%= link_to 'Return Groups', groups_path %>
<%= link_to 'New Key mapping', new_group_key_mapping_path %>

app/views/key_mappings/new.html.erb
<h1>New key_mapping</h1>

<%= render 'form' %>

<%= link_to 'Back', group_key_mappings_path %>

app/views/key_mappings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Key:</b>
  <%= @key_mapping.key %>
</p>

<p>
  <b>Content:</b>
  <%= @key_mapping.content %>
</p>

<p>
  <b>Ordinal:</b>
  <%= @key_mapping.ordinal %>
</p>


<%= link_to 'Edit', edit_group_key_mapping_path(@key_mapping) %> |
<%= link_to 'Back', group_key_mappings_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CheetStock</title>
  <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/2.9.0/build/reset/reset-min.css">
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shared/_group.html.erb
  <div class="dragbox" id="group-<%= group.id %>">
    <div class="group">
      <h2>
        <div class="viewer"><%= group.name %></div>
        <div class="editor"><input type="text" value="<%= group.name %>" /></div>
      </h2>
      <span class="delete-group ui-corner-all ui-icon ui-icon-close"></span>
    </div>
    <div class="key-mapping">
      <table>
        <%= render partial: 'shared/key_mapping', collection: group.key_mappings %>
      </table>
    </div>
    <div class="add-key-mapping" title="新規キーマッピングを追加します"></div>
  </div>

app/views/shared/_key_mapping.html.erb
<tr id="keymapping-<%= key_mapping.id %>">
  <td class="key">
    <div class="viewer"><%= key_mapping.key %></div>
    <div class="editor"><input type="text" value="<%= key_mapping.key %>" /></div>
  </td>
  <td class="content">
    <div class="viewer"><%= key_mapping.content %></div>
    <div class="editor"><input type="text" value="<%= key_mapping.content %>" /></div>
  </td>
  <td class="delete-keymapping"><span class="ui-icon ui-icon ui-icon-circlesmall-close"></span></td>
</tr>

app/views/sheets/_group.html.erb
  <div class="dragbox" id="group-<%= group.id %>">
    <div class="group">
      <h2>
        <div class="viewer"><%= group.name %></div>
        <div class="editor"><input type="text" value="<%= group.name %>" /></div>
      </h2>
      <span class="delete-group ui-corner-all ui-icon ui-icon-close"></span>
    </div>
    <div class="key-mapping">
      <table>
        <%= render partial: 'key_mapping', collection: group.key_mappings %>
      </table>
    </div>
    <div class="add-key-mapping" title="新規キーマッピングを追加します"></div>
  </div>

app/views/sheets/index.html.erb
<h1>vimチートシート</h1>
<div id="add-group" title="新規グループを追加します">
  <a href="#">New</a>
</div>
<% (1..@sheet.max_column).each do |i| %>
<div id="column_<%=i%>" class="column">
<%= render partial: 'shared/group', collection: @groups[i] %>
</div>
<% end %>
<%= hidden_field_tag :authenticity_token, form_authenticity_token %>

<div id="delete-group-msg"　title="グループを削除します">
削除します。
</div>
<div id="delete-keymapping-msg"　title="キーマッピングを削除します">
削除します。
</div>